name: Release

on:
  push:
    tags:
      - "*"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get TAG Version
        id: get_tag
        run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install Dependencies
        run: yarn install

      - name: Build Ui
        run: yarn generate

      - name: Create dist folder
        run: |
          ARTIFACT_NAME="openrport-frontend-${env.TAG}"
          zip -r "${ARTIFACT_NAME}.zip" ./output

      - name: Create Github Release
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const changelog = "New version";
            const release = await github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: `v${env.TAG}`,
              name: `v${env.TAG}`,
              body: changelog
            })
            
      - name: Upload artifacts to Github Release
        uses: actions/upload-artifact@v4
        with: 
          name: package
          path: ${ARTIFACT_NAME}.zip
        
